# https://docs.sourcery.ai/Reference/Configuration/Rule-Settings/
---
ignore:
  - tests/

rule_settings:
  enable:
    - default
    - gpsg
  disable: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.11"

rules: []

metrics:
  quality_threshold: 80.0

github:
  labels: []
  ignore_labels: ["sourcery-ignore"]
  request_review: author
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

proxy:
  no_ssl_verify: false
